document.writeln("<script src=\'https://eqcn.ajz.miesnfu.com/wp-content/plugins/wp-3d-pony/live2dw/lib/L2Dwidget.min.js\'></script>");
document.writeln("<script>");
document.writeln("    var jsonModel = [");
document.writeln("    \'https://unpkg.com/live2d-widget-model-miku@1.0.5/assets/miku.model.json\',");
document.writeln("    \'https://unpkg.com/live2d-widget-model-shizuku@1.0.5/assets/shizuku.model.json\',");
document.writeln("    ];");
document.writeln("    L2Dwidget.init({ ");
document.writeln("        \'model\': { ");
document.writeln("            \'jsonPath\': jsonModel[Math.floor(Math.random()*(jsonModel.length-1))],");
document.writeln("            \'scale\': 1 ");
document.writeln("        }, ");
document.writeln("        \'display\': { ");
document.writeln("            \'position\': \'left\', ");
document.writeln("            \'width\': 66, ");
document.writeln("            \'height\': 90, ");
document.writeln("            \'hOffset\': 10, ");
document.writeln("            \'vOffset\': 0 ");
document.writeln("        }, ");
document.writeln("        \'mobile\': { ");
document.writeln("            \'show\': false ");
document.writeln("        },");
document.writeln("    });");
document.writeln("</script>");
